-- MySQL Script generated by MySQL Workbench
-- Пн 24 дек 2018 05:13:01
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema todo
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema todo
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `todo` DEFAULT CHARACTER SET utf8 ;
USE `todo` ;

-- -----------------------------------------------------
-- Table `todo`.`tasks`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `todo`.`tasks` (
  `id` INT NOT NULL,
  `name` VARCHAR(256) NOT NULL,
  `date` DATE NULL,
  `is_urgent` TINYINT(1) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;


INSERT INTO tasks VALUES (1, 'test1', '2018-12-31', 0);
INSERT INTO tasks VALUES (2, 'test2', '2018-12-31', 0);
INSERT INTO tasks VALUES (3, 'test3', '2018-12-31', 0);
INSERT INTO tasks VALUES (4, 'test4', '2018-12-31', 0);
INSERT INTO tasks VALUES (5, 'test5', '2018-12-31', 0);
INSERT INTO tasks VALUES (6, 'test6', '2018-12-31', 0);
INSERT INTO tasks VALUES (7, 'test7', '2018-12-31', 0);
INSERT INTO tasks VALUES (8, 'test8', '2018-12-31', 0);
INSERT INTO tasks VALUES (9, 'test9', '2018-12-31', 0);